# Build documentation
# See https://github.com/actions/starter-workflows/blob/main/pages/static.yml for starter
# https://github.com/actions/starter-workflows/tree/main/pages
# 
# Currently hosted at https://py.contrails.org
name: Docs

# only build docs on release
on:
  release:
    types:
      - published
    branches:
      - main

  # Allows run manually from the Actions tab
  workflow_dispatch:

# Global variables
env:
  PYCONTRAILS_CACHE_DIR: '${{ github.workspace }}/.cache/pycontrails'

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
    - name: OS Dependencies
      run: sudo apt-get install -y pandoc

    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        cache: 'pip'
        cache-dependency-path: pyproject.toml

    - name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v1'
      with:
        credentials_json: '${{ secrets.GCP_SERVICE_ACCOUNT }}'

    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v1'

    # put bada files in the default location
    - name: BADA files
      run: |
        mkdir ../bada
        gcloud storage cp -r gs://contrails-301217-bada/bada/bada3 ${{ github.workspace }}/../bada/
        gcloud storage cp -r gs://contrails-301217-bada/bada/bada4 ${{ github.workspace }}/../bada/

    # download ERA5 data from pre-cached data on GCP
    - name: pycontrails cache (ERA5 data)
      run: |
        mkdir -p ${{ env.PYCONTRAILS_CACHE_DIR }}
        gcloud storage cp -r gs://contrails-301217-unit-test/doc-test-cache/* ${{ env.PYCONTRAILS_CACHE_DIR }}/

    - name: Install pycontrails (dev)
      run: make dev-install

    - name: Install pycontrails-bada extension
      run: |
        mkdir -p ~/.ssh/ && ssh-keyscan github.com > ~/.ssh/known_hosts
        gcloud secrets versions access latest --secret="contrails-301217-github-ssh-key" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        pip install "pycontrails-bada @ git+ssh://git@github.com/contrailcirrus/pycontrails-bada.git"

    - name: Execute notebooks
      run: |
        make nb-execute

    - name: Build docs
      run: |
        make docs-build
        ls -la docs/_build/html

    - name: Upload artifact
      uses: actions/upload-pages-artifact@v1
      with:
        path: 'docs/_build/html/'

    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v1
