# Run notebook documentation tests from the ground up

name: Notebook tests

on:
  # run on push to main
  push:
    branches:
      - main

  # run on all PRs
  pull_request:

  # Allows run manually from the Actions tab
  workflow_dispatch:

# Global variables
env:
  PYCONTRAILS_CACHE_DIR: '${{ github.workspace }}/.cache/pycontrails'
  BADA_CACHE_DIR: '${{ github.workspace }}/.cache/bada/'

# set from https://github.com/google-github-actions/auth
permissions:
  contents: read
  pages: write

# This allows a subsequently queued workflow run to interrupt previous runs
concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true


jobs:
  unit-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        cache: 'pip'
        cache-dependency-path: pyproject.toml

    - name: Cache pycontrails cache
      id: cache-test
      uses: actions/cache@v3
      with:
        # Note the caches are specific to branches, so we don't need to specify here
        # https://docs.github.com/en/actions/using-workflows/caching-dependencies-to-speed-up-workflows#restrictions-for-accessing-a-cache
        key: pycontrails-cache
        path: |
          ${{ env.PYCONTRAILS_CACHE_DIR }}

    - name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v1'
      with:
        credentials_json: '${{ secrets.GCP_SERVICE_ACCOUNT }}'

    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v1'

    - name: Add .cdsapirc file
      run: |
        gcloud secrets versions access latest --secret="ecmwf-cdsapi-key-file" > ~/.cdsapirc
    
    - name: BADA files
      run: |
        mkdir -p ${{ env.BADA_CACHE_DIR }}
        gcloud storage cp -r gs://contrails-301217-bada/bada/bada3 ${{ env.BADA_CACHE_DIR }}
        gcloud storage cp -r gs://contrails-301217-bada/bada/bada4 ${{ env.BADA_CACHE_DIR }}
        ls -la ${{ env.BADA_CACHE_DIR }}

    - name: Install pycontrails (dev)
      run: make dev-install

    - name: Install pycontrails-bada extension
      run: |
        mkdir -p ~/.ssh/ && ssh-keyscan github.com > ~/.ssh/known_hosts
        gcloud secrets versions access latest --secret="contrails-301217-github-ssh-key" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        pip install "pycontrails-bada @ git+ssh://git@github.com/contrailcirrus/pycontrails-bada.git"

    - Test notebooks
      run: |
        make nb-test

    - Execute notebooks
      run: |
        make nb-execute
