# Run notebook documentation tests from the ground up

name: Notebook tests

on:
  # run on push to main
  push:
    branches:
      - main

  # run on all PRs
  pull_request:

  # Allows run manually from the Actions tab
  workflow_dispatch:

# Global variables
env:
  PYCONTRAILS_CACHE_DIR: '${{ github.workspace }}/.cache/pycontrails'

# set from https://github.com/google-github-actions/auth
permissions:
  contents: read
  pages: write

# This allows a subsequently queued workflow run to interrupt previous runs
concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true


jobs:
  notebook-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        cache: 'pip'
        cache-dependency-path: pyproject.toml

    - name: Cache pycontrails cache
      id: cache-test
      uses: actions/cache@v3
      with:
        key: pycontrails-cache
        path: |
          ${{ env.PYCONTRAILS_CACHE_DIR }}

    - name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v1'
      with:
        credentials_json: '${{ secrets.GCP_SERVICE_ACCOUNT }}'

    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v1'

    # ERA5 data should be cached after the first run
    # but this is here in case the cache is cleared
    - name: Add .cdsapirc file
      run: |
        gcloud secrets versions access latest --secret="ecmwf-cdsapi-key-file" > ~/.cdsapirc
    
    - name: BADA files
      run: |
        mkdir bada
        gcloud storage cp -r gs://contrails-301217-bada/bada/bada3 ${{ github.workspace }}/bada/
        gcloud storage cp -r gs://contrails-301217-bada/bada/bada4 ${{ github.workspace }}/bada/

    - name: Install pycontrails (dev)
      run: make dev-install

    - name: Install pycontrails-bada extension
      run: |
        mkdir -p ~/.ssh/ && ssh-keyscan github.com > ~/.ssh/known_hosts
        gcloud secrets versions access latest --secret="contrails-301217-github-ssh-key" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        pip install "pycontrails-bada @ git+ssh://git@github.com/contrailcirrus/pycontrails-bada.git"

    - name: Test notebooks
      run: |
        make nb-test

    - name: Execute notebooks
      run: |
        make nb-execute
